apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sovannlyna-api-mastervv-certificate
  namespace: sovannlyna-api-mastervv
spec:
  secretName: sovannlyna-api-mastervv-secret-tls
  commonName: sovannlyna-api-mastervv.assessify.org
  dnsNames:
  - sovannlyna-api-mastervv.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
